/**
 * metadata.ts — Centralized metadata generation for all tool responses.
 *
 * Provides professional-use warnings, data freshness tracking, and source authority disclosure.
 */

import type { Database } from '@ansvar/mcp-sqlite';

export interface ResponseMetadata {
  /** Data freshness information */
  data_freshness: DataFreshness;

  /** Professional use disclaimer */
  disclaimer: string;

  /** Source authority disclosure */
  source_authority: SourceAuthority;

  /** Known coverage gaps */
  coverage_gaps: string[];

  /** EU AI Act transparency notice */
  ai_disclosure: string;
}

export interface DataFreshness {
  /** Last database update timestamp */
  statute_last_updated: string | null;

  /** Last case law sync timestamp */
  case_law_last_sync: string | null;

  /** Warning if data appears stale (>30 days) */
  staleness_warning: string | null;
}

export interface SourceAuthority {
  /** Primary data source description */
  primary_source: string;

  /** Authority level assessment */
  authority_level: 'official' | 'community-maintained';

  /** Verification requirement */
  verification_required: string;
}

/**
 * Generate standard metadata for tool responses.
 *
 * This provides consistent professional-use warnings, data freshness tracking,
 * and source authority disclosure across all tools.
 *
 * @param db - Optional database handle. If not provided, data freshness checks are skipped.
 */
export function generateResponseMetadata(db?: Database): ResponseMetadata {
  const dataFreshness = db ? getDataFreshness(db) : getEmptyDataFreshness();
  const sourceAuthority = getSourceAuthority();

  return {
    data_freshness: dataFreshness,
    disclaimer: 'NOT LEGAL ADVICE. This tool is for research purposes only and does not constitute professional legal advice. Always verify citations with official sources before relying on them in legal matters. Users are solely responsible for verifying accuracy and currency of all information.',
    source_authority: sourceAuthority,
    coverage_gaps: [
      'Landesrecht (state-level legislation of 16 Bundeslaender)',
      'CJEU (Court of Justice of the European Union) case law',
      'Historical statute versions (limited availability)',
      'Legal commentary and annotations (Kommentare)'
    ],
    ai_disclosure: 'AI-assisted legal research tool. Results generated by algorithmic search and may contain errors or omissions. Human review required before professional use.'
  };
}

/**
 * Return empty data freshness when database is not available.
 */
function getEmptyDataFreshness(): DataFreshness {
  return {
    statute_last_updated: null,
    case_law_last_sync: null,
    staleness_warning: 'Data freshness information unavailable (tool does not query database)'
  };
}

/**
 * Check data freshness and generate staleness warnings.
 */
function getDataFreshness(db: Database): DataFreshness {
  let statuteLastUpdated: string | null = null;
  try {
    const statuteRow = db.prepare(`
      SELECT MAX(last_updated) as max_date
      FROM legal_documents
      WHERE type = 'statute' AND last_updated IS NOT NULL
    `).get() as { max_date: string | null } | undefined;
    statuteLastUpdated = statuteRow?.max_date || null;
  } catch {
    // Ignore errors
  }

  let caseLawLastSync: string | null = null;
  try {
    const caseRow = db.prepare(`
      SELECT last_sync_date
      FROM case_law_sync_metadata
      WHERE id = 1
    `).get() as { last_sync_date: string } | undefined;
    caseLawLastSync = caseRow?.last_sync_date || null;
  } catch {
    // Table might not exist yet
  }

  const stalenessWarning = calculateStalenessWarning(statuteLastUpdated, caseLawLastSync);

  return {
    statute_last_updated: statuteLastUpdated,
    case_law_last_sync: caseLawLastSync,
    staleness_warning: stalenessWarning
  };
}

/**
 * Generate staleness warning if data is >30 days old.
 */
function calculateStalenessWarning(
  statuteDate: string | null,
  caseLawDate: string | null
): string | null {
  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

  const warnings: string[] = [];

  if (statuteDate) {
    const statuteTimestamp = new Date(statuteDate);
    if (statuteTimestamp < thirtyDaysAgo) {
      const daysOld = Math.floor((now.getTime() - statuteTimestamp.getTime()) / (24 * 60 * 60 * 1000));
      warnings.push(`Statute data is ${daysOld} days old - amendments may have been published in the BGBl`);
    }
  } else {
    warnings.push('Statute update timestamp unavailable');
  }

  if (caseLawDate) {
    const caseLawTimestamp = new Date(caseLawDate);
    if (caseLawTimestamp < thirtyDaysAgo) {
      const daysOld = Math.floor((now.getTime() - caseLawTimestamp.getTime()) / (24 * 60 * 60 * 1000));
      warnings.push(`Case law data is ${daysOld} days old - new decisions may be missing`);
    }
  }

  return warnings.length > 0 ? warnings.join('. ') : null;
}

/**
 * Get source authority disclosure.
 */
function getSourceAuthority(): SourceAuthority {
  return {
    primary_source: 'Gesetze im Internet (gesetze-im-internet.de) and BGBl (Bundesgesetzblatt) for federal statutes; EUR-Lex for EU-reference metadata',
    authority_level: 'official',
    verification_required: 'ALWAYS cross-check with current official publications on gesetze-im-internet.de or BGBl before relying on output in legal or compliance work.'
  };
}

/**
 * Wrapper type for tool responses that includes metadata.
 */
export interface ToolResponse<T> {
  /** Tool-specific results */
  results: T;

  /** Professional-use metadata and warnings */
  _metadata: ResponseMetadata;
}

// ---------------------------------------------------------------------------
// Compliance _meta block (required on all tool responses)
// ---------------------------------------------------------------------------

/**
 * Flat compliance metadata block required on every tool response.
 * Contains disclaimer, data freshness date, copyright, and primary source URL.
 */
export interface ComplianceMeta {
  /** Professional-use disclaimer */
  disclaimer: string;
  /** ISO date (YYYY-MM-DD) of the database build / last ingest */
  data_age: string;
  /** Copyright notice for the underlying data */
  copyright: string;
  /** Primary authoritative source URL */
  source_url: string;
}

/**
 * Build a compliance _meta block for a tool response.
 *
 * @param dataAge  - ISO date string (full timestamp or YYYY-MM-DD) of the DB build date
 * @param sourceUrl - Primary source URL (defaults to gesetze-im-internet.de)
 */
export function responseMeta(dataAge: string, sourceUrl?: string): ComplianceMeta {
  const age = dataAge ? dataAge.substring(0, 10) : new Date().toISOString().substring(0, 10);
  return {
    disclaimer:
      'NOT LEGAL ADVICE. For research purposes only. Always verify with official sources ' +
      'before relying on this data in legal or compliance matters. Users are solely responsible ' +
      'for verifying accuracy and currency of all information.',
    data_age: age,
    copyright:
      '© Bundesrepublik Deutschland. Data from Gesetze-im-Internet published under ' +
      'dl-de/by-2-0 licence (Federal Ministry of Justice, BMJ).',
    source_url: sourceUrl ?? 'https://www.gesetze-im-internet.de',
  };
}
